version: '3.8'

services:
  database:
    container_name: database_nlw
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=certification_nlw